version: 1
packages:
  docker:
    # available types: docker, debian, homebrew
    package_type: docker
    allow_custom_build: true
    # repo where the workflow is started
    repo: redis/docker-library-redis
    # ref to use for workflow runs, if not specified it
    # will be determined based on the tag and existing branches
    # Should be empty for real use cases, is to be used for testing only
    # ref: branch_name
    # build workflow name
    build_workflow: release_build_and_test.yml
    # build workflow timeout in minutes, optional
    build_timeout_minutes: 45
    # static workflow inputs for build workflow
    build_inputs: {}
    # whether to run publish workflow for internal releases
    publish_internal_release: no
    # publish workflow name
    publish_workflow: release_publish.yml
    # publish workflow timeout in minutes, optional
    publish_timeout_minutes: 10
    # static workflow inputs for publish workflow
    publish_inputs: {}
  debian:
    package_type: debian
    repo: redis/redis-debian
    build_workflow: release_build_and_test.yml
    build_inputs: {}
    publish_internal_release: yes
    publish_workflow: release_publish.yml
    publish_timeout_minutes: 10
    publish_inputs: {}
  rpm:
    package_type: rpm
    repo: redis/redis-rpm
    build_workflow: release_build_and_test.yml
    build_inputs: {}
    build_timeout_minutes: 45
    publish_internal_release: yes
    publish_workflow: release_publish.yml
    publish_timeout_minutes: 10
    publish_inputs: {}
  homebrew:
    package_type: homebrew
    repo: redis/homebrew-redis
    # homebrew has one fixed release branch: main
    ref: main
    build_workflow: release_build_and_test.yml
    build_inputs: {}
    publish_internal_release: yes
    publish_workflow: release_publish.yml
    publish_timeout_minutes: 10
    publish_inputs: {}
  snap:
    package_type: snap
    repo: redis/redis-snap
    # snap has one fixed release branch: master
    ref: master
    build_workflow: release_build_and_test.yml
    build_timeout_minutes: 60
    build_inputs: {}
    publish_internal_release: yes
    publish_workflow: release_publish.yml
    publish_timeout_minutes: 10
    publish_inputs: {}
  clientimage:
    repo: redis-developer/cae-client-testing
    ref: main
    package_type: clientimage
    package_display_name: "Client Test Image"
    needs:
      - docker
    description: |
      Client docker image with specific configuration to test all redis clients.
      Image is build on base of docker image
    allow_custom_build: true
    build_workflow: docker-client-libs-test-pre-release.yaml
    build_timeout_minutes: 20
  redis-py:
    repo: redis-developer/redis-oss-release-automation
    package_display_name: Redis-Py Tests
    client_repo: redis/redis-py
    # if not set - detect latest client version
    # client_ref: master
    needs:
      - clientimage
    ref: main
    package_type: clienttest
    description: "redis-py python client for running redis tests"
    allow_custom_build: true
    build_workflow: redis-py.yml
    build_timeout_minutes: 50
  jedis:
    repo: redis-developer/redis-oss-release-automation
    package_display_name: Jedis Tests
    client_repo: redis/jedis
    # client_ref: master
    needs:
      - clientimage
    ref: main
    package_type: clienttest
    description: "jedis java client for running redis tests"
    allow_custom_build: true
    build_workflow: jedis.yml
    build_timeout_minutes: 30
  lettuce:
    repo: redis-developer/redis-oss-release-automation
    package_display_name: Lettuce Tests
    client_repo: redis/lettuce
    # lettuce doesn't have "v" prefix and has .RELEASE at the end of version tags
    version_ref_prefix: "tags/"
    version_ref_pattern: '^tags/(\d+)\.(\d+)\.(\d+).RELEASE$'
    needs:
      - clientimage
    ref: main
    package_type: clienttest
    description: "lettuce java client for running redis tests"
    allow_custom_build: true
    build_workflow: lettuce.yml
    build_timeout_minutes: 30
  go-redis:
    repo: redis-developer/redis-oss-release-automation
    package_display_name: Go-Redis Tests
    client_repo: redis/go-redis
    client_ref: master
    needs:
      - clientimage
    ref: main
    package_type: clienttest
    description: "go-redis go client for running redis tests"
    allow_custom_build: true
    build_workflow: go-redis.yml
    build_timeout_minutes: 30
  node-redis:
    repo: redis-developer/redis-oss-release-automation
    ref: main
    package_display_name: Node-Redis Tests
    client_repo: redis/node-redis
    client_ref: master
    needs:
      - clientimage
    package_type: clienttest
    description: "node-redis node.js client for running redis tests"
    allow_custom_build: true
    build_workflow: node-redis.yml
    build_timeout_minutes: 30
  nredis-stack:
    package_type: clienttest
    package_display_name: NRedisStack Tests
    description: "NRedisStack .NET client for redis tests"
    client_repo: redis/NRedisStack
    client_ref: master
    needs:
      - clientimage
    repo: redis-developer/redis-oss-release-automation
    ref: main
    build_workflow: nredis-stack.yml
    build_timeout_minutes: 30
    allow_custom_build: true
# stackexchange-redis:
#   package_type: clienttest
#   package_display_name: StackExchange.Redis Tests
#   description: "StackExchange.Redis .NET client for redis tests"
#   client_repo: Peter-Sh/StackExchange.Redis
#   #client_repo: StackExchange/StackExchange.Redis
#   client_ref: main
#   needs:
#     - clientimage
#   repo: redis-developer/redis-oss-release-automation
#   ref: main
#   build_workflow: stackexchange-redis.yml
#   build_timeout_minutes: 30
#   allow_custom_build: true
