inputs:
  gh_token:
    description: 'GitHub token to use'
    required: true
  tag:
    description: 'Tag name to create'
    required: true
  ref:
    description: 'SHA of the commit to tag'
    required: true
  message:
    description: 'Tag message (defaults to tag name)'
    required: false

runs:
  using: "composite"
  steps:
    - name: Create verified tag
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      shell: bash
      run: |
        ${{ github.action_path }}/create-tag-verified.sh --ref ${{ inputs.ref }} ${{ inputs.message && format('--message "{0}"', inputs.message) || '' }} ${{ inputs.tag }}