inputs:
  gh_token:
    description: 'GitHub token to use'
    required: true
  from_branch:
    description: 'Branch to merge from'
    required: true
  to_branch:
    description: 'Branch to merge into'
    required: true

outputs:
  merge_commit_sha:
    description: 'SHA of the merge commit if merge was performed'
    value: ${{ steps.merge-branches.outputs.merge_commit_sha }}

runs:
  using: "composite"
  steps:
    - name: Do verified merge
      id: merge-branches
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
      shell: bash
      run: |
        output=$(${{ github.action_path }}/merge-branches-verified.sh --from ${{ inputs.from_branch }} --to ${{ inputs.to_branch }})
        if echo "$output" | grep -Pq '^[0-9a-fA-F]{40,}\s*$'; then
          echo "merge_commit_sha=$output" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"
        else
          echo "No merge commit created"
        fi